### ISSUE TITLE
Different sizes of photos shown on the website

### ISSUE THREAD

**Issue by CicoZhang** [shiltemann/choosegalaxy#1]
Leon's photo is longer than the others. 

![image](https://user-images.githubusercontent.com/11710225/31953283-13fa6b42-b8e3-11e7-820e-d762b6095517.png)

**Comment by shiltemann** [comment]
@CicoZhang thanks, I will look into fixing the template :)

**Comment by shiltemann** [comment]
should be fixed now :)
